# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the starter branch
  push:
    branches: [ starter ]
  pull_request:
    branches: [ starter ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  NODE_VERSION: '14.2.0'                # set this to the node version to use  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "dist/"
          target: "docs/"
      - name: Commit live demo
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: 'docs'
